config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do

  # Authentication
  # @implemented
  devise_for :users

  # Application
  # @implemented
  root to: 'posts#index'
  resources :newsletters, param: :token, only: [:create, :destroy]

  # Account
  # @implemented
  scope :account do
    resources :users, only: [:show, :edit, :update, :destroy]
  end

  # Blog
  # @implemented
  scope :blog do
    resources :categories
    resources :posts
  end

  # API
  # @implemented
  namespace :api do
    namespace :v1 do
      # some json here
    end
    namespace :v2 do
      # some xml here
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, :use => :slugged

  self.table_name  = 'categories'
  self.primary_key = 'id'

  has_many :posts, :dependent => :destroy
  belongs_to :category, optional: true
  belongs_to :user
end

app/models/newsletter.rb
# frozen_string_literal: true

class Newsletter < ApplicationRecord
  self.table_name = 'newsletters'
  self.primary_key = 'id'

  after_create :signup

  def signup
    set_token
    set_status(true)
    set_signup_date
    save!
  end

  def cancel
    remove_token
    set_status(false)
    save!
  end

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 60 }

  validates :email,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 245 }

  validates :token,
            uniqueness: true

  private

  def set_token
    self.token = SecureRandom.urlsafe_base64
  end

  def remove_token
    self.token = nil
  end

  def set_status(status = true)
    self.active = status
  end

  def set_signup_date(date = Date.today)
    self.signup_date = date
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, :use => :slugged

  self.table_name  = 'posts'
  self.primary_key = 'id'

  has_one_attached :thubmnail, :dependent => :destroy

  scope :by_title,    -> (title) {where('title like ?', title) }
  scope :published,   -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }
  scope :by_category, -> (category) { where(category: category) }
  scope :by_user,     -> (user) { where(user: user) }
  scope :recents,     -> { order(created_at: :desc) }
  scope :lasts,       -> { order(created_at: :asc) }
  scope :related,     -> (post) { where(category: post.category) }
  scope :by_year,     -> (year) { where('created_at like ?', "%#{year}%") }

  belongs_to :category
  belongs_to :user

  def self.build_year_cloud
    @years ||= []
    Post.all.each do |post|
        year = post.created_at.year
        next if @years.include?(year)
        @years << year
    end
    @years
  end

  def self.build_tag_cloud
    @tags ||= []
    Post.all.each do |post|
      post.tags.split(/\s/).each do |tag|
        next if @tags.include?(tag)
        @tags << tag
      end
    end
    @tags
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  self.table_name  = 'users'
  self.primary_key = 'id'

  has_one_attached :avatar, :dependent => :destroy

  def give_admin_access
    self.admin = true
    save!
  end

  def revoke_admin_access
    self.admin = false
    save!
  end

  has_many :categories, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

# frozen_string_literal: true

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  def set_global_search
    @search = Post.ransack(params[:q])
  end
  helper_method :set_global_search

  # some code here
  before_action :set_global_search
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to    :html, :json, :js

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def show
    respond_with(@category)
  end

  def create
    @category = current_user.categories.create(category_params)
    respond_with(@category)
  end

  def edit
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, :tags, :category_id)
  end
end

app/controllers/newsletters_controller.rb
# frozen_string_literal: true

class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:destroy]

  def create
    newsletter = Newsletter.find_or_create_by(newsletter_params)
    redirect_to root_path, notice: 'Você se cadastrou com sucesso.'
  end

  def destroy
    @newsletter.cancel
    redirect_to root_path, notice: 'Você cancelou a newsletter com sucesso.'
  end

  private

    def set_newsletter
      @newsletter = Newsletter.find_by_token(params[:token])
    end

    def newsletter_params
      params.require(:newsletter).permit(:name, :email)
    end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  respond_to    :html, :json, :js

  def index
    @newsletter = Newsletter.new
    @search = Post.ransack(params[:q])
    @posts = @search.result(distinct: true).page(params[:page]).per(12)
    respond_with(@posts)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def create
    @post = current_user.posts.create(post_params)
    respond_with(@post)
  end

  def show
    @search = Post.ransack(params[:q])
    respond_with(@post)
  end

  def edit
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post)
      .permit(:title, :description, :content, :published, :tags, :category_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def show
    respond_with(@user)
  end

  def edit
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'Conta removida com sucesso.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user)
      .permit(:avatar, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.haml
= form_for(category) do |f|
  = render 'shared/errors', model: category

  .field
    = f.label :name, 'Nome'
    = f.text_field :name, class: 'form-control', required: 'required',
    placeholder: 'Digite o nome', autocomplete: 'off'
  .field
    = f.label :description, 'Descrição'
    = f.text_area :description, class: 'form-control', required: 'required',
    placeholder: 'Digite a descrição', autocomplete: 'off'
  .field
    = f.label :tags, 'Tags'
    = f.text_field :tags, class: 'form-control', required: 'required',
    placeholder: 'Digite as tags', autocomplete: 'off'
  .field
    = f.label :category_id, 'Categoria'
    = f.collection_select :category_id,
    Category.order(created_at: :desc), :id, :name,
    {prompt: 'Selecionar Categoria'}, {class: 'form-control'}
  .actions
    %br
    = f.submit nil, class: 'btn btn-primary btn-lg top'

app/views/categories/edit.haml
= provide :title, "Editar #{@category.name}"

.container
  .row
    .col-md-12
      = render 'form', category: @category

app/views/categories/index.haml
= provide :title, "Categorias"

.container
  .row
    .col-md-12

app/views/categories/new.haml
= provide :title, "Adicionar Categoria"

.container
  .row
    .col-md-12
      = render 'form', category: @category

app/views/categories/show.haml
= provide :title, @category.name

.container
  .row
    .col-md-12

app/views/layouts/_footer.haml
%footer{class: 'jumbotron'}
  .container
    .row
      .col-md-12

app/views/layouts/_header.haml
%header
  %nav{class: 'navbar navbar-default navbar-fixed-top'}
    .container-fluid{class: 'container'}
      .navbar-header
        %button{type: 'button', class: 'navbar-toggle collapsed', 'data-toggle': 'collapse', 'data-target': '#bs-example-navbar-collapse-1', 'aria-expanded': 'false'}
          %span{class: 'sr-only'} Toggle navigation
          %span{class: 'icon-bar'}
          %span{class: 'icon-bar'}
          %span{class: 'icon-bar'}
        = link_to 'Renato Franco', root_path, class: 'navbar-brand'

      .collapse{class:'navbar-collapse', id: 'bs-example-navbar-collapse-1'}
        %ul{class: 'nav navbar-nav'}
          %li=link_to 'Home', posts_path
          %li=link_to 'Sobre', ''
          %li=link_to 'Blog', ''
          %li=link_to 'Contato', ''

        = search_form_for(@search, html: {class: 'navbar-form navbar-left'}) do |f|
          .form-group
            .input-group
              = f.text_field :title_cont, class: 'form-control', placeholder: 'Buscar...'
              .input-group-addon
                %i{class: 'glyphicon glyphicon-search'}


        %ul{class: 'nav navbar-nav navbar-right'}
          -if (current_user)
            %li= image_tag('', class: 'avatar')
            %li{class: 'dropdown'}
              %a{href: '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown', role: 'button',
              'aria-haspopup': 'true', 'aria-expanded': 'false'}=current_user.name
              %ul{class: 'dropdown-menu'}
                %li=link_to 'Perfil', user_path(current_user)
                %li=link_to 'Editar Perfil', edit_user_path(current_user)
                %li{role: 'separator', class: 'divider'}
                %li=link_to 'Sair', destroy_user_session_path, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Renato Franco - <%= yield :title %></title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css"><%= yield :css %></style>
    <script type="text/javascript"><%= yield :js %></script>
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@3.0.3/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@3.0.3/js/froala_editor.pkgd.min.js'></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-beta.0/css/froala_editor.css">
  </head>
  <body class="<%= controller.controller_name %>">
    <%= render partial: 'layouts/header' %>
    <div id="content" style="margin-top: 70px;">
      <%= yield %>
    </div>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.haml
= form_for(post, html: {multipart: true}) do |f|
  = render 'shared/errors', model: post

  .field
    = f.label :thumbnail, 'Thumbnail'
    = f.file_field :thumbnail
  .field
    = f.label :title, 'Titulo'
    = f.text_field :title, class: 'form-control', required: 'required',
      placeholder: 'Digite o titulo', autocomplete: 'off'
  .field
    = f.label :description, 'Descrição'
    = f.text_area :description, class: 'form-control', required: 'required',
      placeholder: 'Digite a descrição', autocomplete: 'off'
  .field
    = f.label :content, 'Conteudo'
    = f.text_area :description, class: 'form-control', required: 'required',
    placeholder: 'Digite o conteudo', autocomplete: 'off'
  .field
    = f.label :published, 'Publicado?'
    %br
    = f.check_box :published
  .field
    = f.label :tags, 'Tags'
    = f.text_field :tags, class: 'form-control', required: 'required',
    placeholder: 'Digite as tags', autocomplete: 'off'
  .field
    = f.label :category_id, 'Categoria'
    = f.collection_select :category_id,
    Category.order(name: :asc), :id, :name,
    {prompt: 'Selecionar Categoria'}, {class: 'form-control', required: 'required'}
  .actions
    %br
    = f.submit nil, class: 'btn btn-primary btn-lg top'

app/views/posts/edit.haml
= provide :title, "Editar #{@post.title}"

.container
  .row
    .col-md-12
      = render 'form', post: @post

app/views/posts/index.haml
= provide :title, 'Blog'

#presenter{class: 'jumbotron'}
  .row
    .col-md-12

.container
  .row
    .col-md-12
      .col-md-12
        .col-md-12
          %ul{class: 'breadcrumb'}
            %li=link_to 'Home', root_path
            %li=link_to 'Blog', posts_path

      .col-md-8
        .col-md-12
          .well{class: 'text-right'}
            %ul{class: 'list-inline'}
              %li= button_to 'Adicionar Categoria', new_category_path,
                class: 'btn btn-default btn-lg top', method: :get
              %li= button_to 'Adicionar Postagem', new_post_path,
                class: 'btn btn-primary btn-lg top', method: :get

        - @posts.published.recents.limit(12).each do |post|
          .col-md-6
            .panel{class: 'panel-default', id: 'post'}
              .jumbotron
              %div{style: 'padding: 10px;'}
                %h4{id: 'title'}=link_to post.title, post_path(post)
                %p{id: 'description'}=post.description
                =link_to 'Ver mais', post_path(post), class: 'btn btn-primary btn-lg top'

        .col-md-12
          -if @posts.empty?
            .well{class: 'text-center'}
              %p Nenhuma postagem encontrada.

        .col-md-12
          %div{class: 'text-center'}
            = paginate(@posts)

      .col-md-4
        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4 Buscar
            = search_form_for @search do |f|
              .field
                .input-group
                  = f.text_field :title_cont, class: 'form-control',
                  placeholder: 'Buscar...', autocomplete: 'off'
                  .input-group-addon
                    %i{class: 'glyphicon glyphicon-search'}

        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4 Sobre
            .jumbotron
            %h3{class: 'bold'} Renato Franco
            %h5 Desenvolvedor Full-Stack
            %p Apaixonado por desenvolvimento e tecnologias Open Source passo o meu tempo escrevendo sobre tecnologia, empreendedorismo e viagens.

        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4{class: 'bold'} Ultimas postagens
            - @posts.published.recents.limit(5).each do |post|
              .media
                .media-left
                .media-body
                  %h4{class: 'media-heading'}= link_to post.title, post_path(post)
                  %p=post.description

        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4{class: 'bold'} Categorias
            %ul{class: 'list-unstyled'}
              - Category.all.each do |category|
                %li=link_to "#{category.name} - #{category.posts.count}", posts_path(q: {category_cont: category.id})

        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4{class: 'bold'} Tags
            - Post.build_tag_cloud.each do |tag|
              = link_to posts_path(:q, {tags_cont: tag}), method: :get do
                %span{class: 'badge'}=tag

        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4{class: 'bold'} Ano
            %ul{class: 'list-unstyled'}
              - Post.build_year_cloud.sort.reverse.each do |year|
                %li= link_to "#{year} - #{Post.by_year(year).count}", posts_path(:q, {created_at_cont: year})

        .col-md-12
          .panel{class: 'panel-default', style: 'padding: 20px;'}
            %h4{class: 'bold'} Newsletters
            = form_for @newsletter, {url: newsletters_path, method: :post} do |f|
              .field
                = f.label :name, 'Nome Completo'
                .input-group
                  = f.text_field :name, class: 'form-control', required: 'required',
                  placeholder: 'Digite o nome', autocomplete: 'off'
                  .input-group-addon
                    %i{class: 'glyphicon glyphicon-search'}
              .field
                = f.label :email, 'E-mail'
                .input-group
                  = f.email_field :email, class: 'form-control', required: 'required',
                  placeholder: 'Digite o e-mail', autocomplete: 'off'
                  .input-group-addon
                    %i{class: 'glyphicon glyphicon-search'}
              .field
                %br
                = f.submit 'Inscreva-me', class: 'btn btn-primary btn-lg top'

        .col-md-12
          .well
            %h4{class: 'bold'} Renato Franco
            %p Todos os direitos reservados &copy #{Date.today.year}

app/views/posts/new.haml
= provide :title, "Adicionar Postagem"

.container
  .row
    .col-md-12
      = render 'form', post: @post

app/views/posts/show.haml
= provide :title, @post.title

.container
  .row
    .col-md-12
      %ul{class: 'breadcrumb'}
        %li=link_to 'Home', root_path
        %li=link_to @post.title, post_path(@post)

    .col-md-12
      #heading
        .jumbotron
        .col-md-6
          %h1{class: 'bold', id: 'title'}= @post.title
          %p{id: 'description'}= @post.description
        .col-md-6
          .media
            .media-left
              %p=@post.thubmnail
            .media-body
              %h4{class: 'bold'}= @post.user.email
              %p="Postado há #{time_ago_in_words(@post.created_at)}"

    .col-md-12
      #content
        %hp{id: 'body'}= @post.content

    .col-md-12
      #footer
        = @post.tags

    .col-md-12
      #comments
        = render partial: 'shared/disqus'

    .col-md-12
      #related
        - Post.related(@post).limit(3).each do |post|
          .col-md-4
            .panel{class: 'panel-default'}
              .jumbotron
              #content{style: 'padding: 20px;'}
                %h4{class: 'bold'}= link_to post.title, post_path(post)
                %p=post.description
                =link_to 'Ver Mais', post_path(post), class: 'btn btn-primary btn-lg top'

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://renato-franco-2.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the
  <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>

app/views/shared/_errors.haml
- if (model.errors.count > 0)
  .alert{class: 'alert-danger'}
    %ul{class: 'list-unstyled'}
    = model.errors.messages.each do |error|
      %li= "#{error}"

app/views/users/_avatar.haml
= form_for(user) do |f|
  = render 'shared/errors', model: user

  .field
    = f.label :avatar, 'Avatar'
    = f.file_field :avatar
  .field
    = f.submit nil, class: 'btn btn-primary btn-lg top'

app/views/users/_form.haml
= form_for(user) do |f|
  = render 'shared/errors', model: user

  .field
    = f.label :name, 'Nome'
    = f.text_field :name, class: 'form-control', required: 'required',
    placeholder: 'Digit o nome', autocomplete: 'off'
  .field
    = f.label :email, 'E-mail'
    = f.email_field :email, class: 'form-control', required: 'required',
    placeholder: 'Digite o e-mail', autocomplete: 'off'
  .field
    = f.label :password, 'Senha'
    = f.password_field :password, class: 'form-control', required: 'required',
    placeholder: 'Digite a senha', autocomplete: 'off'
  .field
    = f.label :password_confirmation, 'Confirmar senha'
    = f.password_field :password_confirmation, class: 'form-control', required: 'required',
    placeholder: 'Confirme sua Senha', autocomplete: 'off'
  .actions
    %br
    = f.submit nil, class: 'btn btn-primary btn-lg top'

app/views/users/edit.haml
= provide :title, "Editar #{@user.name}"

.container
  .row
    .col-md-12
      = render 'avatar', user: @user
      = render 'form',   user: @user

app/views/users/show.haml
= provide :title, "Perfil de #{@user.name}"

.container
  .row
    .col-md-12